default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: habit_api_user

development:
  <<: *default
  database: habit_api_user_development

test:
  <<: *default
  database: habit_api_user_test

production:
  <<: *default
  database: habit_api_user_production
  password: <%= ENV['HABIT_API_USER_DATABASE_PASSWORD'] %>
