# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de77c20b3fc6e5fe9dd5141765925f7ee45810b474a7cdd4011e9aae84100117e1c769b9c74f32a50e957b633b2b1d978b23d2a3d5c6e5b0175f8f2b7612e01b

test:
  secret_key_base: 2782c7d3956405f7cea84b76919628e745e0a88a232fce8889191eeaee518f4c12e51e2e521c4634962c6f76afcdef8807da7a9d81835c248930257e877f6c8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
